noticias/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('',views.NoticiaListView.as_view(), name='index'),
    path('/about', views.about, name='about'),
    path('busca/',views.busca_noticias,name='busca'),
    path('create/',views.NoticiaCreateView.as_view(),name='create'),
    path('update/<int:pk>/',views.NoticiaUpdateView.as_view(),name="update"),
    path('delete/<int:pk>/',views.NoticiaDeleteView.as_view(),name="delete"),
    path('<int:post_id>/review/', views.create_review, name='review'),
    path('<int:pk>/',views.NoticiaDetailView.as_view(),name="detail"),
]

webnoticias/urls.py
from django.contrib import admin
from django.urls import include, path 

urlpatterns = [
    path('', include('noticias.urls')),
    path('admin/', admin.site.urls),
]

noticias/models.py
from django.db import models
from django.conf import settings
# Create your models here.

class Post(models.Model):
    titulo = models.CharField(max_length=255)
    conteudo = models.TextField()
    data = models.DateTimeField()
    poster_url = models.URLField(max_length=200, null=True)

    def __str__(self):
        return f'{self.titulo} ({self.data})'

class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    text = models.CharField(max_length=25)
    noticia = models.ForeignKey(Post, on_delete=models.CASCADE)
    data = models.DateTimeField()

    def __str__(self):
        return f'"{self.text}" - {self.author.username} - {self.data}'

noticias/forms.py
from django.forms import ModelForm, DateTimeInput
from .models import Comment, Post

class NoticiaForm(ModelForm):
    class Meta:
        model = Post
        fields = [
            'titulo',
            'data',
            'poster_url',
            'conteudo',
        ]
        labels = {
            'titulo': 'Título',
            'data': 'Data de Lançamento',
            'poster_url': 'URL do Poster',
            'conteudo': 'Conteúdo',
        }
        widgets = {
            'data': DateTimeInput(attrs={'type': 'datetime-local'}),
        }

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = [
            "author",
            "text",
            "data",
        ]
        labels = {
            "author": "Usuário",
            "text": "Resenha",
            "data": "Escrito em",
        }
        widgets = {
            'data': DateTimeInput(attrs={'type': 'datetime-local'}),
        }

noticias/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy, reverse
from .models import Post, Comment
from .forms import NoticiaForm, CommentForm
from django.views import generic
from django.http import HttpResponseRedirect

def about(request):
    context = {}
    return render(request, 'noticias/about.html', context)

class NoticiaListView(generic.ListView):
    model = Post
    template_name = 'noticias/index.html'

class NoticiaDetailView(generic.DetailView):
    model = Post
    template_name = 'noticias/detail.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = self.get_object()
        comentarios = Comment.objects.filter(noticia=post)
        context['comentarios'] = comentarios
        return context

def busca_noticias(request):
    context = {}
    if request.GET.get('query',False):
        search_term = request.GET['query'].lower()
        noticias_list = Post.objects.filter(titulo__icontains = search_term)
        context = {'noticias_list':noticias_list}
    return render(request,'noticias/busca.html',context)

class NoticiaCreateView(generic.CreateView):
    model = Post
    template_name = 'noticias/create.html'
    form_class = NoticiaForm
    success_url = reverse_lazy('index')

class NoticiaDeleteView(generic.DeleteView):
    model = Post
    template_name = 'noticias/delete.html'
    success_url = reverse_lazy('index')

class NoticiaUpdateView(generic.UpdateView):
    model = Post
    template_name = 'noticias/update.html'
    form_class = NoticiaForm
    success_url = reverse_lazy('index')

def create_review(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            review_author = form.cleaned_data["author"]
            review_text = form.cleaned_data["text"]
            review_data = form.cleaned_data['data']
            review = Comment(author=review_author, text=review_text, noticia=post, data=review_data)
            review.save()
            return HttpResponseRedirect(reverse("detail", 1))
    else:
        form = CommentForm()
        context = {"form": form, "noticia": post}
        return render(request, "noticias/review.html", context)

noticias/templates/noticias/about.html
{% extends 'base.html' %}

{% block title %}
Sobre
{% endblock title %}

{% block content %}
<h2>Sobre este site</h2>
{% endblock content %}

noticias/templates/noticias/busca.html
{% extends 'base.html' %}

{% block content %}
<h2>Busca de Notícias por Nome</h2>
<form action="{% url 'busca' %}">
    <p>
        <label for="id_query">Título:</label>
        <input type="text" name="query" id="id_query" />
    </p>
    <button type="submit">Buscar</button>
</form>


<h2>Resultado da Busca</h2>
{% if noticias_list %}
<section class="lista-de-cards">
    {% for noticia in noticias_list %}
    <article class="card">
        <a href={% url 'detail' noticia.id%}><img src="{{ noticia.poster_url }}"></a>
        <p>{{ noticia.titulo }} ({{ noticia.data }})</p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrada nenhuma notícia correspondente a sua busca.</p>
{% endif %}

{% endblock content %} 

noticias/templates/noticias/create.html
{% extends 'base.html' %}

{% block content %}
<h2>Inserir Nova Notícia</h2>
<form method="post" action="{% url 'create' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Criar</button>
</form>

{% endblock content %}

noticias/templates/noticias/delete.html
{% extends 'base.html' %}
{% block content %}
<form action="{% url 'delete' post.id %}" method="post">
  {% csrf_token %}
  <p style="padding: 20px;">
    Você tem certeza que deseja apagar a notícia "{{ post.titulo }}"?
  </p>
  <button type="submit">Apagar</button>
</form>
{% endblock content %}

noticias/templates/noticias/detail.html
{% extends 'base.html' %} {% block title %} {{ post.titulo }} ({{
post.data }} {% endblock title %} {% block content %}
<h2>Detalhes da notícia {{ post.titulo }} ({{ post.data }})</h2>

<section class="dados_da_post">
  <img src="{{ post.poster_url }}" alt="Imagem da notícia {{ post.titulo}}" />
  <ul>
    <li>Nome: {{ post.titulo }}</li>
    <li>Data de Lançamento: {{ post.data }}</li>
    <li>Conteúdo: {{post.conteudo}}</li>
    <li><a href="{%url 'update' post.id%}">Atualizar</a></li>
    <li><a href="{% url 'delete' post.id %}">Apagar</a></li>
  </ul>
</section>

<hr>

<section>
    <header>

    <h2>Comentários</h2>
    {% if comentarios %}
        <ul>
            {% for comentario in comentarios %}
                <li>
                    <p>Texto: {{ comentario.text }}</p>
                    <p>Autor: {{ comentario.author.username }}</p>
                    <p>Data: {{ comentario.data }}</p>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Nenhum comentário ainda.</p>
    {% endif %}
        </ul>
<a href="{% url 'review' post.id%}"><button>Crie sua Resenha</button></a>
</section>

{% endblock content %}

noticias/templates/noticias/index.html
{% extends 'base.html' %}

{%block title%}
Home
{%endblock title%}

{%block content%}
    <h1>Bem-vindo a minha página de notícias</h1>
    <p>O conteúdo dessa página é colaborativo, por favor contribua se quiser.</p>
    <h2>Notícias</h2>
    {%if post_list%}
        <section class = 'lista_de_post'>
            {%for n in post_list%}
                <article class="card">
                    <a href="{% url 'detail' n.id %}">
                        <img src="{{ n.poster_url }}" width="400" height="400"/>
                    </a>
                    <p>{{ n.titulo }} ({{ n.data }})</p>
                </article>
            {%endfor%}
        </section>
    {%else%}
        <p>Não foram encontradas notícias</p>
    {%endif%}
{%endblock content%}

noticias/templates/noticias/review.html
{% extends 'base.html' %}
{% block content %}
    <h2>Comentar noticía {{ post.titulo }} ({{ post.data }})</h2>
    <form action="{% url 'review' post_id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Postar Resenha</button>
    </form>
{% endblock content %}

noticias/templates/noticias/update.html
{% extends 'base.html' %}

{% block content %}
<h2>Atualizar Notícia{{ post.titulo }} ({{post.data}})</h2>
<form method="POST" action="{% url 'update' post.id%}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Atualizar</button>
</form>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %} | webnoticias
    </title>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>

<body>
    <header id="cabecalho-principal">
        <nav id="navegacao-principal">
            <ul>
                <img src="{% static 'logo.png' %}" width="40" height="40">
                <h1>WebNotícias</h1>
                <li><a href="{%url 'index'%}">Home</a></li>
                <li><a href="{% url 'about' %}">Sobre</a></li>
                <li><a href="{%url 'create' %}">Adicionar</a></li>
                <li><a href="{%url 'busca' %}">Buscar</a></li> 
            </ul>
        </nav>

    </header>
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer id="rodape-principal">
        <p>
        <small>© 2023 Gabriel</small>
        </p>
    </footer>
</body>

</html>